services:
  # Starter Service
  starter-service:
    build:
      context: .
      dockerfile: services/starter-service/Dockerfile
    container_name: vng-starter-service
    restart: always
    ports:
      - "8080:3000"
    networks:
      - vng-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: vng-notification-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - vng-network

networks:
  vng-network:
    driver: bridge
